keys:
  - &qcoh age1hrk0haltt9qtw440yf3lzvjteglrhv3wcwcq54qv0qz2udukmuzqve33my
  - &lima age1dmccvz232s6vvqylyylefegn4gkveqhf3sgq9v97gahs3nyffc9snn8l44
creation_rules:
  - path_regex: secrets/guest.yaml
    key_groups:
      - age:
          - *qcoh
          - *lima
