services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ed
    ports:
      - "6432:5432"
    volumes:
      - ./etc/compose_init.sql:/docker-entrypoint-initdb.d/init.sql
