services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ed
    ports:
      - "6432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  ed:
    image: ed:latest
    container_name: ed


volumes:
  pgdata:
