-- V1 creates the schema and adds required extensions.

CREATE SCHEMA ed_api AUTHORIZATION ed_api;

GRANT SELECT, INSERT, UPDATE, DELETE
  ON ALL TABLES IN SCHEMA ed_api
  TO ed_api;

ALTER DEFAULT PRIVILEGES IN SCHEMA ed_api
  GRANT SELECT, INSERT, UPDATE, DELETE
  ON TABLES TO ed_api;

CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "vector";
