-- V1 creates the schema and adds required extensions.

CREATE EXTENSION IF NOT EXISTS "vector";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE SCHEMA ed_api AUTHORIZATION edapp;

GRANT SELECT, INSERT, UPDATE, DELETE
  ON ALL TABLES IN SCHEMA ed_api
  TO edapp;

ALTER DEFAULT PRIVILEGES IN SCHEMA ed_api
  GRANT SELECT, INSERT, UPDATE, DELETE
  ON TABLES TO edapp;
